### ISSUE TITLE
Exposure maps timeline

### ISSUE THREAD

**Issue by sarahgeargeoura** [LandSciTech/ccviR#88]
Hello Sarah,

Something that came up in our meeting was the fact that exposure maps until 2050 might not coincide with 3 generation times for some species. I was wondering if a user wants to make the climate data packages themselves, can they include files with climate projections until 2100?

In addition, do you think it would be useful/feasible to have a pre-prepared climate package with projections until 2100 as another option?

Thank you,
Sarah

**Comment by see24** [comment]
@sarahgeargeoura  Yes, users can create a custom data package for any year. I previously removed the parts that specified 2050 in some of the questions and other parts of the app. They should keep in mind though that because the CCVI index values are relative you can not compare a species that was assessed for 2100 with one that was assessed for 2050. 

I added a new prepared data package to the ones on google drive and added a table that explains what is in the different packages as well. The new data package is for the 2080s time period which is a summary over the years 2070-2100
