### ISSUE TITLE
Discrepancy in Figures - Climate Scenario Titles

### ISSUE THREAD

**Issue by sarahgeargeoura** [LandSciTech/ccviR#89]
Hi Sarah!

I just noticed this issue, even after updating the app, where there is a discrepancy in titles for the climate scenarios in the figures. In some instances, they are labeled as RCP and in others SSP. I have attached screenshots of a side-by-side, in which I re-uploaded the results for both these species and I got different results. I have been using both terms interchangeably, but I am not sure if there is a difference. 

I also just noticed that in the exposure maps legend, the RCP 4.5 title is repeated twice.

![image](https://user-images.githubusercontent.com/105516777/222030475-250be2ea-4eab-4385-aa63-f8df9118b74e.png)
![image](https://user-images.githubusercontent.com/105516777/222030516-c6cab450-9573-4894-8b37-605a1910ede6.png)

**Comment by sarahgeargeoura** [comment]
Yes, sorry so these are both examples that I previously completed and re-loaded the data onto the app.

**Comment by see24** [comment]
Conclusion of this was that the name of the folder with climate data had changed which was affecting the loading from saved. The climate data used in the two versions was also different so that is where the different scenario names were coming from. A good example of why the bookmarking way of saving things is tricky, having it saved as a csv would have been much easier to troubleshoot.
