### ISSUE TITLE
Add breaks to exposure map legend and table

### ISSUE THREAD

**Issue by out2lunch22** [LandSciTech/ccviR#93]
The heat map legend has a scale from 1-6 for each scenario. Are these the 1-6 classes listed under the graph? If so, what unit are they in? I have tried looking for a document to interpret the results to no avail. Thanks.

**Comment by see24** [comment]
Yes the 1-6 classes in the map correspond to the classes in the table below. This is described [here](https://landscitech.github.io/ccviR/articles/app_vignette.html). The classes do not have units, they are created by classifying the change in the climate variable, in this case mean annual temperature or climate moisture deficit between the historical normal and future climate projections. The classes are determined by the mean and standard deviation of the change in the climate variable such that the first class is unusually small change 3 and 4 are close to average change and 6 is unusually high change. The classes are determined from the lower change scenario, in this case RCP 4.5 and are applied to RCP 8.5 which is why for temperature it is all 6 for the RCP 8.5 scenario. These details of how the exposure data is classified are described in most detail [here](https://landscitech.github.io/ccviR/articles/package_vignette.html). However, I agree this is confusing and we should make it more clear both within the app and in the app vignette. 

I would also like to store the breaks used to create the classes with the appropriate units in the climate data readme csv that is created when the climate data is processed. Then we could read them from their and use them to label the classes in a more clear way. 

Thanks for flagging this, I will add it to the to do list

- [ ] Add more description of the interpretation of exposure classes to the app and app vignette
- [ ] Record breaks from climate data preparation in the climate data readme and use in exposure table and map legend
